StringUtil.cpp in EmmyLuaCodeStyle requires wildcards lib
Fix for:

```
[59/82] Compile C++ build/obj/code_format/StringUtil.obj
FAILED: build/obj/code_format/StringUtil.obj
gcc -MMD -MT build/obj/code_format/StringUtil.obj -MF build/obj/code_format/StringUtil.obj.d -std=c++17 -O2 -Wall -fvisibility=hidden -I3rd/EmmyLuaCodeStyle/include -I3rd/bee.lua/3rd/lua -DNDEBUG -Wall -Werror -o build/obj/code_format/StringUtil.obj -c 3rd/EmmyLuaCodeStyle/Util/src/StringUtil.cpp
3rd/EmmyLuaCodeStyle/Util/src/StringUtil.cpp:5:10: fatal error: wildcards/match.hpp: No such file or directory
    5 | #include "wildcards/match.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```